const langData = {
    en: {
        home: "Home",beijing:"Beijing",shanghai:"Shanghai",xian:"Xi'an",shanxi:"Shanxi · Black Myth",
        sichuan:"Sichuan",yunnan:"Yunnan",hangzhou:"Hangzhou",guilin:"Guilin",tibet:"Tibet",
        routes:"Travel Routes",contact:"Contact Us",
        banner_title:"Discover the Mysterious Beauty of China",
        banner_desc:"Ancient Heritage · Natural Wonders · Authentic Experiences",
        dest_title:"Popular Destinations",
        beijing_desc:"Great Wall & Forbidden City, the heart of ancient China.",
        beijing_header: "Beijing - The Capital of China",
        history_title: "📜 History Introduction",
        history_desc: "Beijing is the capital and political, cultural center of China, with a 3,000-year history and 800 years as an imperial capital. It perfectly blends ancient imperial heritage like the Great Wall with a modern international skyline, a city where the past meets the future.",
        top_attractions: "🏞️ Top Attractions",
        atr1_title: "The Great Wall of China",
        atr1_desc: "One of the Seven Wonders of the World, a symbol of China's ancient civilization. The Mutianyu section offers stunning mountain views and well-preserved ancient architecture.",
        atr2_title: "The Forbidden City",
        atr2_desc: "The imperial palace of Ming & Qing dynasties, the largest wooden palace complex in the world. A UNESCO Heritage Site with grand palaces and priceless cultural relics.",
        atr3_title: "The Summer Palace",
        atr3_desc: "China's largest imperial garden, a masterpiece of landscape gardening with lakes, pavilions and temples.",
        popular_routes_title: "🗺️ Popular Travel Routes",
        classic_3day_title: "Classic 3-Day Beijing Tour",
        classic_3day_desc: "Day 1: Tiananmen Square → Forbidden City → Jingshan Park<br>Day 2: Mutianyu Great Wall → Olympic Park<br>Day 3: Summer Palace → Lama Temple → Hutong Tour",
        // Shanghai specific
        shanghai_header: "Shanghai - China's Pearl of the East",
        sh_history_desc: "Shanghai is China's economic and financial heart, a vibrant metropolis on the Yangtze River estuary. From a small fishing village to a global city, it blends Eastern traditions with Western colonial architecture and modern skyscrapers.",
        sh_atr1_title: "The Bund",
        sh_atr1_desc: "A historic waterfront with European-style buildings, facing the modern Lujiazui skyline across the Huangpu River - a perfect contrast of old and new.",
        sh_atr2_title: "Yu Garden & Old Town",
        sh_atr2_desc: "A classical Ming Dynasty garden with exquisite rockeries and ponds, surrounded by traditional alleys and local snack streets.",
        sh_atr3_title: "Shanghai Disneyland",
        sh_atr3_desc: "A magical fairy-tale world with unique Chinese-themed attractions, the perfect family travel destination.",
        sh_classic_2day_title: "2-Day Modern & Traditional Tour",
        sh_classic_2day_desc: "Day 1: The Bund → Lujiazui → Nanjing Road<br>Day 2: Yu Garden → French Concession → Xintiandi",
        // Xi'an specific (English)
        xian_header: "Xi'an - Ancient Capital of China",
        xi_history_desc: "Xi'an, formerly Chang'an, is one of China's Four Great Ancient Capitals, serving 13 dynasties for over 3,100 years. It is the starting point of the Silk Road and the birthplace of Chinese civilization, home to countless ancient relics.",
        xi_atr1_title: "Terracotta Army",
        xi_atr1_desc: "The Eighth Wonder of the World, an underground army of thousands of clay soldiers built for Qin Shi Huang. A UNESCO Heritage Site and a breathtaking ancient masterpiece.",
        xi_atr2_title: "Xi'an City Wall",
        xi_atr2_desc: "China's most complete ancient city wall, built in the Ming Dynasty. Cycle along the wall for panoramic views of the old town and modern city.",
        xi_atr3_title: "Giant Wild Goose Pagoda",
        xi_atr3_desc: "A Tang Dynasty Buddhist pagoda built to store scriptures, surrounded by a beautiful park and musical fountain.",
        xi_classic_3day_title: "3-Day Ancient Culture Tour",
        xi_classic_3day_desc: "Day 1: Terracotta Army → Huaqing Pool<br>Day 2: City Wall → Bell Tower → Muslim Quarter<br>Day 3: Giant Wild Goose Pagoda → Shaanxi History Museum",
        // Shanxi (English)
        shanxi_header: "Shanxi - Black Myth: Wukong's Real Homeland",
        shanxi_history_desc: "Shanxi is a treasure trove of ancient Chinese architecture and Buddhist culture, with over 20,000 ancient buildings dating back 1,500 years. It inspired the hit game Black Myth: Wukong with stunning grottoes and temples.",
        shanxi_atr1_title: "Yungang Grottoes",
        shanxi_atr1_desc: "One of China's four great grottoes, with 53 caves and 51,000 stone Buddha statues. The main inspiration for the game's heavenly cave scenes.",
        shanxi_atr2_title: "Hanging Temple",
        shanxi_atr2_desc: "A miraculous temple built into a cliff 1,500 years ago, suspended by wooden beams with no nails. A blend of three religions.",
        shanxi_atr3_title: "Yingxian Wooden Pagoda",
        shanxi_atr3_desc: "The oldest wooden pagoda in the world, built without nails over 900 years ago - a masterpiece of ancient engineering.",
        shanxi_4day_title: "4-Day Black Myth Pilgrimage Tour",
        shanxi_4day_desc: "Day 1: Yungang Grottoes → Hanging Temple<br>Day 2: Yingxian Wooden Pagoda → Mount Heng<br>Day 3: Pingyao Ancient City → Qiao Family Compound<br>Day 4: Shuanglin Temple → Jinci Temple",
        // Yunnan (English)
        yunnan_header: "Yunnan - Rainbow Land of Ethnic Cultures",
        yun_history_desc: "Yunnan is a magical land of 25 ethnic minorities, stunning alpine lakes and tropical rainforests. It was a key stop on the ancient Tea Horse Road, with a rich blend of Chinese and Southeast Asian cultures.",
        yun_atr1_title: "Lijiang Ancient Town",
        yun_atr1_desc: "A UNESCO Heritage Site with stone streets, wooden houses and canals - a romantic ancient town with Naxi culture.",
        yun_atr2_title: "Dali Erhai Lake",
        yun_atr2_desc: "A crystal lake surrounded by snow mountains and Bai villages, perfect for cycling and relaxing.",
        yun_atr3_title: "Xishuangbanna Rainforest",
        yun_atr3_desc: "A lush tropical forest with elephant sanctuaries and Dai water festivals, a taste of Southeast Asia in China.",
        yun_5day_title: "5-Day Yunnan Classic Tour",
        yun_5day_desc: "Day1: Kunming Stone Forest<br>Day2-3: Dali (Erhai Lake, Three Pagodas)<br>Day4-5: Lijiang (Old Town, Jade Dragon Snow Mountain)",
        // Guilin (English)
        guilin_header: "Guilin - Landscape Beyond Imagination",
        gu_history_desc: "Guilin is world-famous for its karst mountain and Li River scenery, printed on China's 20-yuan note. With a 2,100-year history, it blends Han and Zhuang cultures and is one of China's most iconic natural destinations.",
        gu_atr1_title: "Li River Cruise",
        gu_atr1_desc: "A 4-hour boat ride from Guilin to Yangshuo, passing stunning karst peaks and fishing villages - the highlight of any trip.",
        gu_atr2_title: "Yangshuo West Street",
        gu_atr2_desc: "A vibrant pedestrian street with cafes, bars and local snacks, perfect for relaxing after sightseeing.",
        gu_atr3_title: "Reed Flute Cave",
        gu_atr3_desc: "A magical underground cave with colorful stalactites and stalagmites, known as the \"Palace of Natural Arts\".",
        gu_classic_3day_title: "3-Day Guilin & Yangshuo Tour",
        gu_classic_3day_desc: "Day1: Guilin (Elephant Trunk Hill, Reed Flute Cave)<br>Day2: Li River Cruise → Yangshuo West Street<br>Day3: Yulong River Bamboo Raft → Moon Hill",
        // Sichuan (English)
        sichuan_header: "Sichuan - Land of Pandas & Spicy Delights",
        sichuan_history_desc: "Sichuan Province, located in southwest China, is known as the \"Land of Abundance\" for its fertile plains and rich natural resources. It has a long history of over 2,000 years, with unique culture, beautiful scenery and world-famous Sichuan cuisine.",
        sc_atr1_title: "Chengdu Panda Base",
        sc_atr1_desc: "Home to over 100 giant pandas and red pandas; visitors can observe pandas and learn about conservation efforts.",
        sc_atr2_title: "Jiuzhaigou Valley",
        sc_atr2_desc: "A UNESCO World Heritage Site known for colorful alpine lakes, waterfalls and snow-capped mountains.",
        sc_atr3_title: "Mount Emei & Leshan Giant Buddha",
        sc_atr3_desc: "Sacred Mount Emei and the Leshan Giant Buddha (71m), an awe-inspiring cliff-carved statue.",
        sc_7day_title: "7-Day Classic Sichuan Tour (Recommended)",
        sc_7day_desc: "Day 1-2: Chengdu (Panda Base, Jinli Ancient Street, Sichuan Hot Pot)<br>Day 3-4: Jiuzhaigou Valley & Huanglong Scenic Area<br>Day 5: Leshan Giant Buddha<br>Day 6-7: Mount Emei (Golden Summit)",
        // Hangzhou (English)
        hangzhou_header: "Hangzhou - Paradise on Earth",
        hang_history_desc: "Hangzhou is known as \"Paradise on Earth\" for its West Lake and silk culture. It was the Southern Song Dynasty capital, with a 2,200-year history and a perfect blend of natural beauty and cultural heritage.",
        hang_atr1_title: "West Lake",
        hang_atr1_desc: "A UNESCO Heritage Site with ten scenic spots, immortalized in Chinese poetry - the soul of Hangzhou.",
        hang_atr2_title: "Longjing Tea Village",
        hang_atr2_desc: "A picturesque village famous for premium green tea, where you can pick tea leaves and learn tea-making.",
        hang_atr3_title: "Lingyin Temple",
        hang_atr3_desc: "A thousand-year-old Buddhist temple surrounded by mountains and ancient stone carvings.",
        hang_classic_2day_title: "2-Day Hangzhou Leisure Tour",
        hang_classic_2day_desc: "Day1: West Lake Boat Tour → Su Causeway → Leifeng Pagoda<br>Day2: Longjing Tea Village → Grand Canal Night Cruise",
        // Tibet (English)
        tibet_header: "Tibet - Roof of the World",
        tibet_history_desc: "Tibet, the \"Roof of the World\", is on the Qinghai-Tibet Plateau with an average altitude of 4,000 meters. It has a unique Tibetan Buddhist culture, ancient monasteries and sacred mountains.",
        tib_atr1_title: "Potala Palace",
        tib_atr1_desc: "A UNESCO Heritage Site and Tibet's symbol, a magnificent palace built on a hill in Lhasa with priceless Buddhist relics.",
        tib_atr2_title: "Jokhang Temple",
        tib_atr2_desc: "Tibet's holiest temple, attracting pilgrims from across the plateau every day.",
        tib_atr3_title: "Namtso Lake",
        tib_atr3_desc: "One of Tibet's three sacred lakes, a crystal blue lake surrounded by snow mountains and grasslands.",
        tib_classic_7day_title: "7-Day Lhasa & Surroundings Tour",
        tib_classic_7day_desc: "Day1-2: Lhasa (Potala Palace, Jokhang Temple)<br>Day3: Namtso Lake → Yangbajing Hot Springs<br>Day4-5: Shigatse & Everest Base Camp<br>Day6-7: Ganden Monastery → Lhasa Departure",
        xian_desc:"Terracotta Army & Tang Dynasty culture, the glory of old China.",
        shanxi_desc:"Black Myth: Wukong real prototype & ancient grottoes.",
        sichuan_desc:"Giant Pandas, Jiuzhaigou & spicy Sichuan cuisine.",
        guilin_desc:"Li River & karst mountains, the poetic landscape of China.",
        hangzhou_desc:"West Lake & silk culture, the beauty of southern China.",
        myth_title:"Black Myth: Wukong · Shanxi Real Prototype",
        myth_desc:"The hit game <b>Black Myth: Wukong</b> takes all core scenes from Shanxi's 1500-year-old architecture. Visit Yungang Grottoes, Hanging Temple, Yingxian Wooden Tower - the real places that inspired the game's stunning visuals.",
        myth_btn:"Explore Shanxi Details",
        route_title:"Premium Travel Routes",
        food_title:"Authentic Chinese Cuisine",
        footer:"Explore China © 2026 | All Rights Reserved"
    },
    zh: {
        home: "首页",beijing:"北京",shanghai:"上海",xian:"西安",shanxi:"山西 · 黑神话",
        sichuan:"四川",yunnan:"云南",hangzhou:"杭州",guilin:"桂林",tibet:"西藏",
        routes:"旅游线路",contact:"联系我们",
        banner_title:"发现中国的神秘之美",
        banner_desc:"古老遗产 · 自然奇观 · 地道体验",
        dest_title:"热门目的地",
        beijing_desc:"长城与故宫，中华古都之心。",
        beijing_header: "北京 - 中国的首都",
        history_title: "📜 历史简介",
        history_desc: "北京是中国的首都和政治文化中心，拥有3000年的历史和800年的建都史。这里既有长城等古代皇朝遗产，也有现代国际化的天际线，是古今交汇的城市。",
        top_attractions: "🏞️ 主要景点",
        atr1_title: "长城",
        atr1_desc: "世界七大奇迹之一，中国古代文明的象征。慕田峪段山色壮丽，古建筑保存良好。",
        atr2_title: "故宫",
        atr2_desc: "明清两代的皇家宫殿，世界上规模最大的木结构宫殿群。联合国教科文组织世界遗产。",
        atr3_title: "颐和园",
        atr3_desc: "中国规模最大的皇家园林，湖光山色、亭台楼阁与寺庙相映成趣。",
        popular_routes_title: "🗺️ 热门旅游线路",
        classic_3day_title: "经典北京三日游",
        classic_3day_desc: "第1天：天安门广场 → 故宫 → 景山公园<br>第2天：慕田峪长城 → 奥林匹克公园<br>第3天：颐和园 → 雍和宫 → 胡同漫游",
        // 上海翻译
        shanghai_header: "上海 - 东方明珠",
        sh_history_desc: "上海是中国的经济和金融中心，位于长江入海口的繁华都会。从小渔村发展为国际大都市，兼具东方传统与西方租界建筑和现代摩天楼。",
        sh_atr1_title: "外滩",
        sh_atr1_desc: "一条充满欧洲风格建筑的历史滨江大道，对面是陆家嘴现代天际线，古今交织。",
        sh_atr2_title: "豫园与老城",
        sh_atr2_desc: "明代园林，假山池沼精致，周边是传统街巷与地道小吃。",
        sh_atr3_title: "上海迪士尼乐园",
        sh_atr3_desc: "拥有中国特色的主题项目，适合家庭旅行的奇幻世界。",
        sh_classic_2day_title: "2日现代与传统游",
        sh_classic_2day_desc: "第1天：外滩 → 陆家嘴 → 南京路<br>第2天：豫园 → 法租界 → 新天地",
        // 西安翻译
        xian_header: "西安 - 古都长安",
        xi_history_desc: "西安，古称长安，是中华四大古都之一，13个朝代建都，3000多年历史，是丝绸之路起点，中国文明的关键发源地之一，拥有无数文物古迹。",
        xi_atr1_title: "兵马俑",
        xi_atr1_desc: "世界第八大奇迹，秦始皇陵的地下军队，成千上万陶俑栩栩如生，联合国教科文组织世界遗产。",
        xi_atr2_title: "西安城墙",
        xi_atr2_desc: "明代建成的保存最完好的古城墙，骑行可俯瞰古城与现代城市景观。",
        xi_atr3_title: "大雁塔",
        xi_atr3_desc: "唐代佛塔，曾用于藏经，周围公园与音乐喷泉相映成趣。",
        xi_classic_3day_title: "三日古文化游",
        xi_classic_3day_desc: "第1天：兵马俑 → 华清池<br>第2天：城墙 → 钟楼 → 回民街<br>第3天：大雁塔 → 陕西历史博物馆",
        // 山西翻译
        shanxi_header: "山西 - 黑神话：悟空的实景原乡",
        shanxi_history_desc: "山西是中国古建筑与佛教文化的宝库，拥有超过2万座古建筑，可追溯1500年。它是热门游戏《黑神话：悟空》的实景灵感来源，石窟与古寺令人惊叹。",
        shanxi_atr1_title: "云冈石窟",
        shanxi_atr1_desc: "中国四大石窟之一，53个洞窟与5.1万尊石佛，是游戏中“天洞”场景的重要原型。",
        shanxi_atr2_title: "悬空寺",
        shanxi_atr2_desc: "建于悬崖之中的奇观，1500年前以木梁悬挑，融儒释道三教于一体。",
        shanxi_atr3_title: "应县木塔",
        shanxi_atr3_desc: "世界上最古老的木结构塔楼之一，千年风雨而成的工程奇迹。",
        shanxi_4day_title: "4天黑神话朝圣线路",
        shanxi_4day_desc: "第1天：云冈石窟 → 悬空寺<br>第2天：应县木塔 → 恒山<br>第3天：平遥古城 → 乔家大院<br>第4天：双林寺 → 晋祠",
        // 云南翻译
        yunnan_header: "云南 - 多彩民族之地",
        yun_history_desc: "云南是一个充满魔力的地方，拥有25个少数民族、壮丽的高山湖泊和热带雨林。古代茶马古道的重要驿站，文化兼具中国与东南亚特色。",
        yun_atr1_title: "丽江古城",
        yun_atr1_desc: "世界文化遗产，石板街道、木屋与水道交织的浪漫古镇，纳西族文化浓厚。",
        yun_atr2_title: "大理洱海",
        yun_atr2_desc: "群山环抱的澄澈湖泊，白族村落点缀其间，适合骑行与放松。",
        yun_atr3_title: "西双版纳雨林",
        yun_atr3_desc: "热带雨林、象群保护区与傣族泼水节，感受东南亚风情。",
        yun_5day_title: "云南五日经典游",
        yun_5day_desc: "第1天：昆明石林<br>第2-3天：大理（洱海、三塔）<br>第4-5天：丽江（古城、玉龙雪山）",
        // 四川翻译
        sichuan_header: "四川 - 熊猫与麻辣美食之乡",
        sichuan_history_desc: "四川位于中国西南，被誉为天府之国，历史悠久，文化独特，山水秀美，且美食享誉全国，是大熊猫的故乡。",
        sc_atr1_title: "成都大熊猫繁育研究基地",
        sc_atr1_desc: "这里有上百只大熊猫与小熊猫，游客可近距离观察并了解保护工作。",
        sc_atr2_title: "九寨沟",
        sc_atr2_desc: "联合国教科文组织世界遗产，以五彩斑斓的高山湖泊、瀑布与雪山著称。",
        sc_atr3_title: "峨眉山与乐山大佛",
        sc_atr3_desc: "峨眉山为佛教圣山，乐山大佛为世界上最大的坐佛石刻之一。",
        sc_7day_title: "7日四川经典游（推荐）",
        sc_7day_desc: "第1-2天：成都（大熊猫基地、锦里古街、川式火锅）<br>第3-4天：九寨沟与黄龙景区<br>第5天：乐山大佛<br>第6-7天：峨眉山（金顶)",
        // 桂林翻译
        guilin_header: "桂林 - 山水甲天下",
        gu_history_desc: "桂林以喀斯特山水与漓江风光闻名，常见于中国20元纸币。拥有2100年历史，汉族与壮族文化交融，是中国最具代表性的自然目的地之一。",
        gu_atr1_title: "漓江游船",
        gu_atr1_desc: "从桂林到阳朔约4小时的船程，途经壮丽喀斯特山峰与渔村，是旅行亮点。",
        gu_atr2_title: "阳朔西街",
        gu_atr2_desc: "热闹的步行街，咖啡馆、酒吧与当地小吃，是观光后的放松好去处。",
        gu_atr3_title: "芦笛岩",
        gu_atr3_desc: "色彩斑斓的地下溶洞，被称为“天然艺术宫”。",
        gu_classic_3day_title: "桂林阳朔三日游",
        gu_classic_3day_desc: "第1天：象鼻山、芦笛岩<br>第2天：漓江游船 → 阳朔西街<br>第3天：遇龙河竹筏 → 月亮山",
        // 杭州翻译
        hangzhou_header: "杭州 - 人间天堂",
        hang_history_desc: "杭州以西湖与丝绸文化闻名，自古有“人间天堂”之称，南宋曾为都城，历史与自然美景交融。",
        hang_atr1_title: "西湖",
        hang_atr1_desc: "世界文化遗产，十景名胜常为诗词所咏，杭州之魂。",
        hang_atr2_title: "龙井茶村",
        hang_atr2_desc: "以优质绿茶闻名，可体验采茶与制茶过程。",
        hang_atr3_title: "灵隐寺",
        hang_atr3_desc: "千年佛寺，山水与古石刻环绕。",
        hang_classic_2day_title: "2日杭州悠闲游",
        hang_classic_2day_desc: "第1天：西湖游船 → 苏堤 → 雷峰塔<br>第2天：龙井茶村 → 大运河夜游",
        xian_desc:"兵马俑与唐文化，中华盛世荣光。",
        shanxi_desc:"黑神话悟空实景原型与千年石窟。",
        sichuan_desc:"大熊猫、九寨沟与麻辣川菜。",
        guilin_desc:"漓江山水，中国诗意画卷。",
        hangzhou_desc:"西湖与丝绸，江南水乡之美。",
        myth_title:"黑神话：悟空 · 山西实景原型",
        myth_desc:"爆款游戏<b>黑神话：悟空</b>核心场景均取材山西千年古建筑，云冈石窟、悬空寺皆是游戏蓝本。",
        myth_btn:"查看山西详情",
        route_title:"精品旅游线路",
        food_title:"地道中国美食",
        footer:"探索中国 © 2026 | 版权所有"
    },
    ja: {
        home: "ホーム",beijing:"北京",shanghai:"上海",xian:"西安",shanxi:"山西･黒神話",
        sichuan:"四川",yunnan:"云南",hangzhou:"杭州",guilin:"桂林",tibet:"チベット",
        routes:"旅行ルート",contact:"お問い合わせ",
        banner_title:"中国の神秘的な美しさを発見",
        dest_title:"人気の旅行先",route_title:"プレミアム旅行ルート",
        myth_btn:"山西の詳細を見る",
        beijing_header: "北京 - 中国の首都",
        history_title: "歴史紹介",
        history_desc: "北京は中国の首都であり、政治・文化の中心です。長い歴史と豊かな遺産があります。",
        footer: "Explore China © 2026 | All Rights Reserved",
        shanghai_header: "上海 - 東洋の真珠",
        sh_history_desc: "上海は中国の経済・金融の中心で、長江河口に位置する活気ある大都市です。",
        sh_atr1_title: "外灘",
        sh_atr2_title: "豫園と老街",
        sh_classic_2day_title: "2日間の近代と伝統ツアー",
        xian_header: "西安 - 古代の都",
        xi_history_desc: "西安（古称長安）は中国の古代都で、多くの王朝の都が置かれた歴史ある都市です。",
        xi_atr1_title: "兵馬俑",
        xi_classic_3day_title: "3日間の古文化ツアー",
        shanxi_header: "山西 - 黒神話：悟空の故地",
        shanxi_history_desc: "山西は古代建築と仏教文化の宝庫で、多くの洞窟や寺院があり、ゲーム『黒神話：悟空』の舞台となった場所です。",
        shanxi_atr1_title: "雲崗石窟",
        shanxi_4day_title: "4日間の黒神話巡礼ツアー",
        yunnan_header: "雲南 - 多民族の色彩あふれる地",
        yun_history_desc: "雲南は多くの少数民族や美しい高山湖、熱帯雨林を有する地域で、かつて茶馬古道の要所でした。",
        yun_atr1_title: "麗江古城",
        yun_5day_title: "5日間の雲南クラシックツアー",
        guilin_header: "桂林 - 想像を超える風景",
        gu_history_desc: "桂林はカルスト地形と漓江の景観で有名で、中国の20元紙幣にも描かれています。",
        gu_atr1_title: "漓江クルーズ",
        gu_classic_3day_title: "桂林・陽朔 3日間ツアー",
        sichuan_header: "四川 - 熊猫と辛ウマ料理の国",
        sichuan_history_desc: "四川は中国南西部に位置し、肥沃な平野と豊かな自然資源で知られます。長い歴史と独自の文化、美しい景観、世界的に有名な四川料理を誇ります。",
        sc_atr1_title: "成都パンダ基地",
        sc_7day_title: "7日間の四川クラシックツアー",
        tibet_header: "チベット - 世界の屋根",
        tibet_history_desc: "チベットは青蔵高原に位置し、標高約4000mの高地です。独自のチベット仏教文化や古い僧院があります。",
        tib_atr1_title: "ポタラ宮",
        tib_classic_7day_title: "ラサと周辺 7日間ツアー",
        hangzhou_header: "杭州 - 人間の楽園",
        hang_history_desc: "杭州は西湖と絹文化で知られ、南宋時代には都が置かれた歴史ある都市です。",
        hang_atr1_title: "西湖",
        hang_classic_2day_title: "2日間の杭州ゆったりツアー"
    },
    ko: {
        home: "홈",beijing:"북경",shanghai:"상하이",xian:"서안",shanxi:"산시·흑신화",
        sichuan:"사천",yunnan:"운남",hangzhou:"항저우",guilin:"계림",tibet:"티벳",
        routes:"여행 노선",contact:"연락처",
        banner_title:"중국의 신비로운 아름다움을 발견하다",
        dest_title:"인기 여행지",route_title:"프리미엄 여행 노선",
        myth_btn:"산시 상세 보기",
        beijing_header: "베이징 - 중국의 수도",
        history_title: "역사 소개",
        history_desc: "베이징은 중국의 수도이자 정치·문화의 중심지로 오랜 역사와 유구한 유산을 자랑합니다.",
        footer: "Explore China © 2026 | All Rights Reserved",
        shanghai_header: "상하이 - 동방의 진주",
        sh_history_desc: "상하이는 중국의 경제·금융 중심지로, 장강 하구의 활기찬 대도시입니다.",
        sh_atr1_title: "와이탄(외탄)",
        sh_atr2_title: "위위안(豫園)과 올드타운",
        sh_classic_2day_title: "2일 현대와 전통 투어",
        xian_header: "시안 - 고대의 수도",
        xi_history_desc: "시안(옛 이름: 장안)은 중국의 고대 수도 중 하나로 오랜 역사와 풍부한 문화유산을 지니고 있습니다.",
        xi_atr1_title: "병마용",
        xi_classic_3day_title: "3일 고대 문화 투어",
        shanxi_header: "산시 - 블랙 미스: 우공의 실사 고향",
        shanxi_history_desc: "산시는 고대 건축과 불교 문화의 보고로, 게임 'Black Myth: Wukong'의 실사 배경이 된 장소입니다.",
        shanxi_atr1_title: "융강석굴",
        shanxi_4day_title: "4일 블랙 미스 순례 투어",
        yunnan_header: "윈난 - 다채로운 민족의 땅",
        yun_history_desc: "윈난은 25개 소수민족과 빼어난 고산호수, 열대우림을 가진 신비로운 지역으로, 고대 차마고도의 중요한 거점이었습니다.",
        yun_atr1_title: "리장 고성",
        yun_5day_title: "5일 윈난 클래식 투어",
        guilin_header: "구이린 - 상상을 초월한 풍경",
        gu_history_desc: "구이린은 카르스트 지형과 리장 경치로 유명하며, 중국 20위안 지폐에 그려져 있습니다.",
        gu_atr1_title: "리강 유람선",
        gu_classic_3day_title: "구이린·양수오 3일 투어",
        tibet_header: "티베트 - 세계의 지붕",
        tibet_history_desc: "티베트는 청장 고원에 위치해 평균 해발 약 4000m입니다. 독특한 티베트 불교 문화와 고대 사원이 있는 신성한 땅입니다.",
        tib_atr1_title: "포탈라 궁전",
        tib_classic_7day_title: "라싸 및 주변 7일 투어",
        hangzhou_header: "항저우 - 천국 같은 곳",
        hang_history_desc: "항저우는 서호와 비단 문화로 유명하며, 남송 시기에 수도였던 역사 깊은 도시입니다.",
        hang_atr1_title: "서호(웨스레이크)",
        hang_classic_2day_title: "2일 항저우 여유 투어"
        ,sichuan_header: "쓰촨 - 팬더와 매콤한 미식의 고장",
        sichuan_history_desc: "쓰촨은 중국 남서부에 위치하며 비옥한 평야와 풍부한 자연자원으로 알려져 있습니다. 오랜 역사와 독특한 문화, 아름다운 자연경관, 세계적으로 유명한 쓰촨 요리를 자랑합니다.",
        sc_atr1_title: "청두 팬더 기지",
        sc_7day_title: "7일 쓰촨 클래식 투어"
    }
};
let currentLang = "en";
function setLang(lang) {
    currentLang = lang;
    document.querySelectorAll('.lang').forEach(el => {
        const key = el.getAttribute('data-key');
        if (langData[lang][key]) el.innerHTML = langData[lang][key];
    });
}
window.onload = () => setLang("en");
